export const data = JSON.parse(`[
        "recipe":{ 
          "label": "Gluten-free Spring Flatbread Pizza",
          "image": "https:/https://img.jamieoliver.com/jamieoliver/recipe-database/E_iSiCE7KrJ8Den8g72CRe.jpg?tr=w-800,h-1066",
          "ingredients": [
            "250 ml milk",
"1 x 7 g sachet of yeast",
"2½ teaspoons caster sugar",
"65 g cornflour",
"425 g brown rice flour , plus extra for dusting",
"2 teaspoons gluten-free xanthan gum",
"1 large free-range egg",
"olive oil",
"½ teaspoon bicarbonate of soda",
"2 teaspoons cider vinegar",
"300 g fresh or frozen peas",
"½ bunch of fresh mint",
"250 g soft goats cheese or curd",
"1 lemon",
"2 courgettes",
"fine polenta for dusting",
"200 g watercress",
"extra virgin olive oil",
          ],
        }, 
        "recipe":{
          "label": "Quick Grilled Pizza",
          "image": "https://img.jamieoliver.com/jamieoliver/recipe-database/64-qiy3pKRAA9WjmFAJrzu.jpg?tr=w-800,h-1066",
          "ingredients": [
           "250 g strong bread flour",
           "2 teaspoons dried yeast",
           "1 teaspoon caster sugar",
           "olive oil",
           "2 cloves of garlic",
           "1 x 400 g tin of chopped tomatoes",
           "a few sprigs of fresh basil", 
          ],
        },    
      ]`);
